cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>/',views.full_remove,name='full_remove'),
]

order/urls.py
from django.urls import path
from . import views

app_name='order'

urlpatterns=[
    path('thanks/<int:order_id>',views.thanks,name='thanks'),
    path('history/',views.orderHistory,name='order_history'),
    path('<int:order_id>/',views.viewOrder,name='order_detail'),
]

shop/urls.py
from django.urls import path
from . import views

app_name='shop'

urlpatterns=[
    path('',views.allProdCat,name='allProdCat'),
    path('<slug:c_slug>/',views.allProdCat,name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>',views.prodCatDetails,name='prodCatDetails'),
]

shoppingsite/urls.py
from django.contrib import admin
from django.urls import path,include
from shop import views
from django.conf import settings
from django.conf.urls.static import static
from shop import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/',include('shop.urls')),
    path('search/',include('search_app.urls')),
    path('cart/',include('cart.urls')),
    path('order/',include('order.urls')),
    path('account/create/',views.signupView,name='signup'),
    path('account/signin/',views.signinView,name='signin'),
    path('account/signout/',views.signoutView,name='signout'),

]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

order/models.py
from django.db import models

class Order(models.Model):
	token = models.CharField(max_length=250, blank=True)
	total = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='GBP Order Total')
	emailAddress = models.EmailField(max_length=250, blank=True, verbose_name='Email Address')
	created = models.DateTimeField(auto_now_add=True)
	billingName = models.CharField(max_length=250, blank=True)
	billingAddress1 = models.CharField(max_length=250, blank=True)
	billingCity = models.CharField(max_length=250, blank=True)
	billingPostcode = models.CharField(max_length=10, blank=True)
	billingCountry = models.CharField(max_length=200, blank=True)
	shippingName = models.CharField(max_length=250, blank=True)
	shippingAddress1 = models.CharField(max_length=250, blank=True)
	shippingCity = models.CharField(max_length=250, blank=True)
	shippingPostcode = models.CharField(max_length=10, blank=True)
	shippingCountry = models.CharField(max_length=200, blank=True)

	class Meta:
		db_table = 'Order'
		ordering = ['-created'] # -created for in order to have latest on top

	def __str__(self):
		return str(self.id)


class OrderItem(models.Model):
	product = models.CharField(max_length=250)
	quantity = models.IntegerField()
	price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='GBP Price')
	order = models.ForeignKey(Order, on_delete=models.CASCADE)

	class Meta:
		db_table = 'OrderItem'

	def sub_total(self):
		return self.quantity * self.price

	def __str__(self):
		return self.product

order/views.py
from django.shortcuts import render, get_object_or_404
from .models import Order,OrderItem
from django.contrib.auth.decorators import login_required
# Create your views here.

def thanks(request,order_id):
    if order_id:
        customer_order=get_object_or_404(Order,id=order_id)
    return render(request,'thanks.html',{'customer_order':customer_order})

@login_required()
def orderHistory(request):
    if request.user.is_authenticated:
        email=str(request.user.email)
        order_details= Order.objects.filter(emailAddress=email)
    return render(request,'order/order_list.html',{'order_details':order_details})

@login_required()
def viewOrder(request,order_id):
    if request.user.is_authenticated:
        email=str(request.user.email)
        order=Order.objects.get(id=order_id,emailAddress=email)
        order_items=OrderItem.objects.filter(order=order)
    return render(request,'order/order_detail.html',{'order':order,'order_items':order_items})
    

order/templates/order/order_detail.html
{% extends "shop/base.html" %}
{% load static%}
{% block title %}
	Order Details - Perfect Cushion Store
{% endblock %}
{% block content %}
	<div>
		<div class="text-center">
			<br>
			<h1 class="text-center my_title">Order Details</h1>
			<br>
			<table class="table table-bordered">
				<tr>
					<td class="text-left" colspan="2">
						<b>Order: </b>#{{ order.id }}<br>
						<b>Date: </b>{{ order.created|date:"d M Y" }}<br>
						<b>Order Total: </b>£{{ order.total }}<br>
						<b>Order Status: </b><i class="fas fa-check"></i> Complete.
					</td>
					<td class="text-left" colspan="2">
						<b>Billing Address: </b><br>
						{{ order.billingName }}<br>
						{{ order.billingAddress1 }}<br>
						{{ order.billingCity }}<br>
						{{ order.billingPostcode }}<br>
						{{ order.billingCountry }}<br>
					</td>
				</tr>
				<tr>
					<td><b>Product Description</b></td>
					<td><b>Qty</b></td>
					<td><b>Unit Price</b></td>
					<td><b>Sub-Total</b></td>
				</tr>
				{% for item in order_items %}
				<tr>
					<td>{{ item.product }}</td>
					<td>{{ item.quantity }}</td>
					<td>£{{ item.price }}</td>
					<td>£{{ item.sub_total }}</td>
				</tr>
				{% endfor %}
				<tr>
					<td class="text-right" colspan="3"><b>Total</b></td>
					<td>£{{ order.total }}</td>
				</tr>
				<tr>
					<td class="text-right" colspan="3"><b>Total Paid</b></td>
					<td>£{{ order.total }}</td>
				</tr>
				<tr>
					<td class="text-left" colspan="2">
						<b>Shipping Address: </b><br>
						{{ order.shippingName }}<br>
						{{ order.shippingAddress1 }}<br>
						{{ order.shippingCity }}<br>
						{{ order.shippingPostcode }}<br>
						{{ order.shippingCountry }}<br>
					</td>
					<td class="text-left" colspan="2">
						<b>Payment Details: </b><br>
						The order #{{ order.id }} has been paid successfully via Stripe.
					</td>
				</tr>
			</table>
			<button class="btn btn-secondary" onclick="window.print();"><i class="fas fa-print"></i>Print Order</button>
		</div>
	</div>
	<br>
	<br>
{% endblock %}

order/templates/order/order_list.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
  Order History - Perfect Cushion Store
{% endblock %}

{% block content %}
  <div class="">
    <div class="text-center">
      <br>
      <h1 class="text-center my_title"> Order History</h1>
      <br>
      {% if order_details %}
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Order Number</th>
              <th>Order Date</th>
              <th>Total Amount</th>
              <th>Status</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            {% for order in order_details  %}
              <tr>
                <td>{{order.id}}</td>
                <td>{{order.created | date:"d M Y"}}</td>
                <td>{{order.total}}</td>
                <td><i class="fas fa-check"></i>&nbsp;Complete</td>
                <td> <a href="{% url 'order:order_detail' order.id %}">View Order</a> </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      {% else %}
      <p>You have not placed any orders yet. <br><br> <a href="{% url 'shop:allProdCat'%}" class="btn btn-secondary">Continue Shopping</a> </p>
      {% endif %}
    </div>

  </div>
  <br>
  <br>
{% endblock %}