cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>/',views.full_remove,name='full_remove'),
]

order/urls.py
from django.urls import path
from . import views

app_name='order'

urlpatterns=[
    path('thanks/<int:order_id>',views.thanks,name='thanks'),
    path('history/',views.orderHistory,name='order_history'),
    path('<int:order_id>/',views.viewOrder,name='order_detail'),
]

search_app/urls.py
from django.urls import path
from . import views

app_name='search_app'

urlpatterns=[
    path('',views.searchResult,name='searchResult'),
]

shop/urls.py
from django.urls import path
from . import views

app_name='shop'

urlpatterns=[
    path('',views.allProdCat,name='allProdCat'),
    path('<slug:c_slug>/',views.allProdCat,name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>',views.prodCatDetails,name='prodCatDetails'),
]

shoppingsite/urls.py
from django.contrib import admin
from django.urls import path,include
from shop import views
from django.conf import settings
from django.conf.urls.static import static
from shop import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/',include('shop.urls')),
    path('search/',include('search_app.urls')),
    path('cart/',include('cart.urls')),
    path('order/',include('order.urls')),
    path('account/create/',views.signupView,name='signup'),
    path('account/signin/',views.signinView,name='signin'),
    path('account/signout/',views.signoutView,name='signout'),

]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models
from django.urls import reverse
# Create your models here.

class Category(models.Model):
    name= models.CharField(max_length=250,unique=True)
    slug = models.SlugField(max_length=250,unique=True)
    description= models.TextField(blank=True)
    image=models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name='category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('shop:products_by_category',args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)


class Product(models.Model):
    name= models.CharField(max_length=250,unique=True)
    slug = models.SlugField(max_length=250,unique=True)
    description= models.TextField(blank=True)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10,decimal_places=2)
    image=models.ImageField(upload_to='product',blank=True)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name='product'
        verbose_name_plural = 'products'

    def get_url(self):
        return reverse('shop:prodCatDetails',args=[self.category.slug,self.slug])

    def __str__(self):
        return '{}'.format(self.name)

shop/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=100, required=True)
    last_name = forms.CharField(max_length=100, required=True)
    email = forms.EmailField(max_length=254, help_text='eg. youremail@anyemail.com')

    class Meta:
	    model = User
	    fields = ('first_name','last_name','email','username','password1','password2')

shop/views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.http import HttpResponse
from .models import Category, Product
from django.core.paginator import Paginator, EmptyPage, InvalidPage
from django.contrib.auth.models import Group,User
from .forms import SignUpForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login,authenticate,logout

# Create your views here.

def allProdCat(request,c_slug=None):
    c_page= None
    products_list=None
    if c_slug!=None:
        c_page=get_object_or_404(Category,slug=c_slug)
        products_list = Product.objects.filter(category=c_page,available=True)
    else:
        products_list =Product.objects.all().filter(available=True)
        '''Paginator code'''
        paginator= Paginator(products_list,6)
        try:
            page= int(request.GET.get('page','1'))
        except:
            page=1
        try:
            products=paginator.page(page)
        except(InvalidPage,EmptyPage):
            products=paginator.page(paginator.num_pages)

    return render(request,'shop/category.html',{'category':c_page,'products':products})

def prodCatDetails(request,c_slug,product_slug):
    try:
        product=Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e

    return render(request,'shop/product.html',{'product':product})


def signupView(request):
    if request.method=='POST':
        form=SignUpForm(request.POST)
        if form.is_valid():
            form.save()
        username= form.cleaned_data.get('username')
        signup_user=User.objects.filter(username=username).first()
        customer_group=Group.objects.get(name='Customer')
        customer_group.user_set.add(signup_user)

    else:
        form=SignUpForm()
    return render(request,'accounts/signup.html',{'form':form})


def signinView(request):
    if request.method=='POST':
        form=AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username,password=password)
            if user is not None:
                login(request, user)
                return redirect('shop:allProdCat')
            else:
                return redirect('signup')
    else:
        form =AuthenticationForm()
    return render(request,'accounts/signin.html',{'form':form})


def signoutView(request):
	logout(request)
	return redirect('signin')

shop/templates/shop/base.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="{% block metadescription %}{%endblock%}">

    <link rel="stylesheet" type="text/css" href="{% static 'css/all.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}" >
    <link rel="stylesheet" href="{% static 'css/custom.css'%}?{% now "U"%}" >

    <title>{% block title %}{%endblock%}</title>
  </head>
  <body>
    <div class="container">
      <div class="container-fluid bg-light navbar-fixed-top my_top_navbar_div">
        {% include 'shop/top-navbar.html' %}
      </div>
      {% include 'shop/header.html'%}
      {% include 'shop/navbar.html'%}
      {% block content %}

      {% endblock %}

    </div>
      {% include 'shop/footer.html' %}

      <script src="{% static 'js/jquery-3.5.1.slim.min.js'%}" ></script>
      <script src="{% static 'js/popper.min.js'%}" ></script>
      <script src="{% static 'js/bootstrap.min.js'%}"></script>
  </body>
</html>

shop/templates/shop/category.html
{% extends "shop/base.html" %}
{% load static %}
{% block metadescription %}
  {% if category %}
    {{ category.description|truncatewords:155 }}
  {% else%}
    Welcome to the cushion store, where you can buy comfy and awesome cushions.
  {% endif %}
{% endblock %}
{% block title%}
{% if category %}
  {{ category.name }} - Perfect Cushions Store
{% else%}
  See our cushions collection
{% endif %}
{% endblock %}
{% block content %}

  {% if category %}
    <div class="row my_row_class">
      <div class="mx-auto ">
        <p><a href="{% url 'shop:allProdCat' %}">Our Product collection</a>| {{category.name}}</p>
      </div>
    </div>
  {% endif %}
  <div class="mx-auto">
    {% if category %}
      <img class="my_image" src="{{category.image.url}}" alt="{{category.name}}">
    </div>
    <br>
    <div class="">
      <h1 class="text-center my_title">{{category.name}}</h1>
      <p class="text-justify">{{category.description}}</p>
    </div>

  {% else %}
  <img class="my_image my_image_padding" src="{% static 'img/banner.jpg'%}" alt="Our Products Collection">
    </div>
    <br>
    <div class="">
      <h1 class="text-center my_title">Our Products Collection</h1>
      <p class="text-justify">Real good cushions</p>
    </div>
  {% endif %}

  <div class="container">
    <div class="row mx-auto">
      {% for product in products.object_list  %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-md-12 col-lg-4">
          <div class="card text-center" style="min-width: 18rem;">
            <a href="{{product.get_url}}"> <img class="card-img-top my_image" src="{{product.image.url}}" alt={{product.name}}> </a>
            <div class="card-body">
              <h4>{{product.name}}</h4>
              <p>{{product.price}}</p>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
    <div class="mx-auto">
      {% if products.paginator.num_pages > 1 %}
        <hr>
        <div class="text-center">
          {% for pg in products.paginator.page_range  %}
            <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %}active{% endif %}">{{pg}}</a>
          {% endfor %}
        </div>
      {% endif %}
    </div>
    <br>
  </div>
{% endblock %}

shop/templates/shop/footer.html
<div class="footer navbar-fixed-bottom my_footer">
  <p class="text-center">E-commerce website. All Rights Reserved</p>
</div>

shop/templates/shop/header.html
{% load static %}

<header>
  <center>
    <img href="{% url 'shop:allProdCat' %}" src="{%static 'img/logo.png' %}" alt="Perfect Cushion Store">
  </center>
</header>

shop/templates/shop/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown {% if 'shop' in request.path %}active{% endif %}">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Shop
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'shop:allProdCat'%}">All Products</a>
            {% for cat in links  %}
          <a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a>
          {% endfor%}
        </div>
      </li>

      <li class="nav-item">
        <a class="nav-link secondary" href="{% url 'cart:cart_detail'%}"><i class="fas fa-shopping-cart"></i>{% if item_count > 0 %}({{item_count}}){% endif %}</a>
      </li>

    </ul>
    <form class="form-inline my-2 my-lg-0" action="{% url 'search_app:searchResult'%}" method="get">
      {% csrf_token %}
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
      <button class="btn btn-secondary" type="submit"><i class="fas fa-search"></i></button>
    </form>
  </div>
</nav>

shop/templates/shop/product.html
{% extends "shop/base.html" %}
{% load static %}
{% block metadescription %}
  {{product.description| truncatewords:155}}
{% endblock %}

{% block title %}
  {{product.name}} - Perfect Cushions Store
{% endblock %}

{% block content %}

  <div class="row my_prod_row_class">
    <div class="mx-auto">
      <p> <a href="{% url 'shop:allProdCat' %}">Home</a> | <a href="{{ product.category.get_url }}">{{product.category}}</a> | {{product.name}} </p>
    </div>
    <div class="container">
      <br>
      <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
          <div style="min-width:18 rem;" class="">
            <img src="{{product.image.url}}" alt="product.name">
          </div>
        </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6">
          <div class="">
            <h1 class="my_prod_title">{{product.name}}</h1>
            <p>{{product.price}} INR</p>
            <p class="my_title">Product Description</p>
            <p class="text-justify my_prod_text">{{product.description}}</p>
            {% if product.stock <= 0 %}
            <p class="text-justify my_prod_text"> <b>Out of Stock</b> </p>
            {% else %}
            <a  class="btn btn-secondary"href="{% url 'cart:add_cart' product.id %}">Add to Cart</a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

shop/templates/shop/top-navbar.html
<div class="container">
	<div class="my_custom_menu">
		<ul>
			{% if request.user.is_authenticated and request.user.first_name %}
			<li>
				Welcome, <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ request.user.first_name }} <i class="fas fa-user-circle"></i></a>
				<div class="dropdown-menu dropdown-menu-right">
					<a href="{% url 'order:order_history'%}" class="dropdown-item">Order History</a>
				</div>
			</li>
			<li>
				<a href="{% url 'signout' %}">Sign Out<i class="fas fa-sign-out-alt"></i></a>
			</li>
			{% else %}
			<li>
				<a href="{% url 'signup' %}">Sign Up <i class="fas fa-user-plus"></i></a>
			</li>
			<li>
				<a href="{% url 'signin' %}">Sign In <i class="fas fa-sign-in-alt"></i></a>
			</li>
			{% endif %}
		</ul>

	</div>
</div>